### ISSUE TITLE
话说程序和cqhttp是不是不能远程，我内网和外网ip都试了不行

### ISSUE THREAD

**Issue by mcc1095319343** [Widecss/ChatGPT-Bot#2]
如题

**Comment by Widecss** [comment]
请提供连接错误时输出的异常日志，以及可以的话请提供程序配置文件和cqhttp配置文件中的网络部分

**Comment by mcc1095319343** [comment]
启动完毕~
Cannot connect to host (cqhttp的外网或内网ip都不行):8080 ssl:default [信号灯超时时间已到]
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\py39\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\ProgramData\Anaconda3\envs\py39\lib\asyncio\base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "D:\ProgramData\Anaconda3\envs\py39\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "D:\ProgramData\Anaconda3\envs\py39\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\ProgramData\Anaconda3\envs\py39\lib\asyncio\proactor_events.py", line 703, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\ProgramData\Anaconda3\envs\py39\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "D:\ProgramData\Anaconda3\envs\py39\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Data\Fun2\ChatGPT-QQBot\cqhttp.py", line 60, in loop
    await self.loop_connect(api, session)
  File "D:\Data\Fun2\ChatGPT-QQBot\cqhttp.py", line 44, in loop_connect
    async with session.ws_connect(ServerURL) as client:
  File "D:\ProgramData\Anaconda3\envs\py39\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\ProgramData\Anaconda3\envs\py39\lib\site-packages\aiohttp\client.py", line 779, in _ws_connect
    resp = await self.request(
  File "D:\ProgramData\Anaconda3\envs\py39\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "D:\ProgramData\Anaconda3\envs\py39\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\ProgramData\Anaconda3\envs\py39\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\ProgramData\Anaconda3\envs\py39\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\ProgramData\Anaconda3\envs\py39\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\ProgramData\Anaconda3\envs\py39\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 115.236.9.97:8080 ssl:default [信号灯超时时间已到]

# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器
  # 正向WS设置
  - ws:
      # 正向WS服务器监听地址
      address: 127.0.0.1:8080(这个换成0.0.0.0也不行)
      middlewares:
        <<: *default # 引用默认中间件

**Comment by Widecss** [comment]
看起来也许是远程主机无法互联，请打开 **cmd** 输入以下指令，并将其中的 **[ip]** 与 **[port]** 替换为 cqhttp 的，以测试 cqhttp 服务器的正向 Websocket 是否通畅：

~~~cmd
curl -i -N -H "Upgrade: websocket" -H "Connection: upgrade" -H "Sec-WebSocket-Version: 13" -H "Sec-WebSocket-Key: abc123" http://[ip]:[port]
~~~

若网络通畅，会显示 **101 Switching Protocols**：
~~~
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: 8ycCYM6DyGcfcT9zgJL+T5KaH5s=
~~~

否则会显示类似如下的连接错误：
~~~
curl: (7) Failed to connect to 100.79.57.127 port 6701 after 3860 ms: Connection refused
~~~
